name: Full Stack App Workflow

# Ensure the workflow runs on schedule (Sunday at 0:00) and on push to the main branch
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'

#Use a matrix strategy to use Node.js versions 16.x and 18.x
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16,18]
        platform: [ubuntu-latest]
    steps:
      # Check out the code from the repository.
      - name: Checkout code
        uses: actions/checkout@v3
      # Set up a Node.js environment using the specified node version.
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Install the dependencies.
      - name: Install Dependencies
        run: cd backend && npm ci

      # Run the tests.
      - name: Build and Test
        run: cd backend && npm test
        continue-on-error: true

      # Run the linter.
      - name: lint 
        run: cd backend && npm run lint

      # Send a console message at completion.
      - run: |
          echo "Hello ${{github.actor}}. You pushed to ${{github.repository}} at $(date)."

        
